apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
      volume.kubernetes.io/selected-node: ip-10-0-133-217.eu-central-1.compute.internal
    creationTimestamp: "2020-05-28T16:06:37Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: quotesdb-claim
    namespace: guusvanderkleij-gmail-com-quotes-dev
    resourceVersion: "142822194"
    selfLink: /api/v1/namespaces/guusvanderkleij-gmail-com-quotes-dev/persistentvolumeclaims/quotesdb-claim
    uid: 35848f6e-a0fd-11ea-84ed-068ec670666c
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 300Mi
    storageClassName: gp2
    volumeMode: Filesystem
    volumeName: pvc-35848f6e-a0fd-11ea-84ed-068ec670666c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
